# .streamlit/secrets.toml

[connections.snowflake]
account = "mckesson.east-us-2.azure"
user = "Hazim.Rashid@mckesson.com"
authenticator = "EXTERNALBROWSER"
role = "Sbx_ea_general_fr"
warehouse = "Sbx_ea_general_fr_wh"
database = "SBX_PSAS_DB"
schema = "ANALYTICS"
client_session_keep_alive = true
